### ISSUE TITLE
Cognizant is not a product based company

### ISSUE THREAD

**Issue by rishadali19** [Kaustubh-Natuskar/moreThanFAANGM#201]
Cognizant purely is a service based company. And  yes it is one of the MNC.

**Comment by AnkittSharmaa** [comment]
Will you assign me this issue?

**Comment by Kaustubh-Natuskar** [comment]
Having a job is better than being unemployed.

**Comment by Kaustubh-Natuskar** [comment]
> @Kaustubh-Natuskar Agree. As you listing product based companies, Cognizant not belongs to this category as it is neither a startup nor a product based company. That’s the only thing I pointed out

Yeah i understand what you want to say brother, but as now i have started job hunting now i have understood how difficult to get a job into pbc's and startups as a student from tier-3 college student.
That's why getting a job a and removing that freshers tag is priority. That's why I've decided to add service based companies on the list too. So that of anyone is searching for a job they'll atleast have a chace.
